apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: docker.io/benmarsden/gol-backend-prod
      context: config_service
    - image: docker.io/benmarsden/gol-frontend-prod
      context: app
deploy:
  kubectl:
    manifests:
      - ./app/app.yml
      - ./config_service/config_service.yml
      - ./ingress/ingress.yml
      - ./ingress/ingress2.yml
      - ./ingress.yml
profiles:
  - name: production
    ## This profile pushes the image
    build:
      local: 
        push: true
      artifacts:
      - image: docker.io/benmarsden/gol-backend-prod
        context: config_service
      - image: docker.io/benmarsden/gol-backend-prod
        context: app
    deploy: {} #flux will take care of this