apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: docker.io/benmarsden/gol-backend-prod
      context: config_service
    - image: docker.io/benmarsden/gol-frontend-prod
      context: app
deploy:
  kubectl:
    manifests:
      - ./app/app.yml
      - ./config_service/config_service.yml
      - ./ingress-controller/controller.yml
      - ./ingress-controller/controller-service.yml
      - ./application-ingress.yml
profiles:
  - name: production
    ## This profile builds and pushes both frontend and backend
    build:
      local: 
        push: true
      artifacts:
      - image: docker.io/benmarsden/gol-backend-prod
        context: config_service
      - image: docker.io/benmarsden/gol-frontend-prod
        context: app
    deploy: {} #flux will take care of this
  - name: demo
    ## This profile builds and pushes only backend, designed for demo use
    build:
      local: 
        push: true
      artifacts:
      - image: docker.io/benmarsden/gol-backend-prod
        context: config_service
    deploy: {} #flux will take care of this
