env:
    browser: true
    es6: true
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended"
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 2018
    sourceType: module
plugins:
    - "@typescript-eslint"
rules:
    indent:
        - error
        - 4
    quotes:
        - error
        - double
    semi:
        - error
        - always
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/ban-ts-ignore": off
    "@typescript-eslint/no-non-null-assertion": off
